#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rabbitmq-server
Version  : 3.5.4
Release  : 36
URL      : https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.4/rabbitmq-server-3.5.4.tar.gz
Source0  : https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.4/rabbitmq-server-3.5.4.tar.gz
Source1  : rabbitmq-server.service
Source2  : rabbitmq-server.tmpfiles
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause HPND MIT MPL-1.1 MPL-2.0
Requires: rabbitmq-server-bin
Requires: rabbitmq-server-config
BuildRequires : libxslt-bin
BuildRequires : otp
BuildRequires : python
BuildRequires : zip
Patch1: remove-docs.patch
Patch2: 0001-remove-netcat-buildreq.patch
Patch3: 0001-Add-bin-wrapper.patch
Patch4: 0001-Initial-hostname-fix.patch

%description


%package bin
Summary: bin components for the rabbitmq-server package.
Group: Binaries
Requires: rabbitmq-server-config

%description bin
bin components for the rabbitmq-server package.


%package config
Summary: config components for the rabbitmq-server package.
Group: Default

%description config
config components for the rabbitmq-server package.


%prep
%setup -q -n rabbitmq-server-3.5.4
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install TARGET_DIR=%{buildroot}/usr/lib/rabbitmq/lib/rabbitmq-server SBIN_DIR=%{buildroot}/usr/lib/rabbitmq/bin MAN_DIR=%{buildroot}%{_mandir} DOC_INSTALL_DIR=%{buildroot}%{_defaultdocdir}
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/rabbitmq-server.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/tmpfiles.d/rabbitmq-server.conf
## make_install_append content
install -d -m 755 %{buildroot}%{_sbindir}
install -m 755 rabbitmq-script-wrapper %{buildroot}%{_sbindir}/rabbitmqctl
install -m 755 rabbitmq-script-wrapper %{buildroot}%{_sbindir}/rabbitmq-server
install -m 755 rabbitmq-script-wrapper %{buildroot}%{_sbindir}/rabbitmq-plugins
## make_install_append end

%files
%defattr(-,root,root,-)
/usr/lib/rabbitmq/bin/rabbitmq-defaults
/usr/lib/rabbitmq/bin/rabbitmq-env
/usr/lib/rabbitmq/bin/rabbitmq-plugins
/usr/lib/rabbitmq/bin/rabbitmq-server
/usr/lib/rabbitmq/bin/rabbitmqctl
/usr/lib/rabbitmq/lib/rabbitmq-server/INSTALL
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-APACHE2-ExplorerCanvas
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-APL2-Stomp-Websocket
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-Apache-Basho
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-BSD-base64js
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-BSD-glMatrix
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-MIT-EJS10
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-MIT-Flot
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-MIT-Mochi
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-MIT-Sammy060
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-MIT-eldap
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-MIT-jQuery164
/usr/lib/rabbitmq/lib/rabbitmq-server/LICENSE-MPL-RabbitMQ
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/app_utils.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/background_gc.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/credit_flow.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/delegate.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/delegate_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/dtree.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/file_handle_cache.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/file_handle_cache_stats.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/gatherer.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/gen_server2.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/gm.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/lqueue.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/mirrored_supervisor.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/mirrored_supervisor_sups.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/mnesia_sync.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/mochijson2.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/mochinum.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/pg2_fixed.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/pg_local.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/pmon.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/priority_queue.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit.app
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_access_control.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_alarm.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_amqqueue.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_amqqueue_process.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_amqqueue_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_amqqueue_sup_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_app.in
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_auth_backend_dummy.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_auth_backend_internal.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_auth_mechanism.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_auth_mechanism_amqplain.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_auth_mechanism_cr_demo.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_auth_mechanism_plain.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_authn_backend.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_authz_backend.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_autoheal.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_backing_queue.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_basic.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_binary_generator.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_binary_parser.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_binding.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_channel.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_channel_interceptor.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_channel_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_channel_sup_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_cli.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_client_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_command_assembler.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_connection_helper_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_connection_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_control_main.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_ctl_usage.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_dead_letter.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_diagnostics.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_direct.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_disk_monitor.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_epmd_monitor.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_error_logger.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_error_logger_file_h.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_event.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_exchange.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_exchange_decorator.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_exchange_type.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_exchange_type_direct.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_exchange_type_fanout.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_exchange_type_headers.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_exchange_type_invalid.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_exchange_type_topic.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_file.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_framing.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_framing_amqp_0_8.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_framing_amqp_0_9_1.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_guid.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_heartbeat.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_limiter.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_log.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_memory_monitor.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mirror_queue_coordinator.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mirror_queue_master.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mirror_queue_misc.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mirror_queue_mode.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mirror_queue_mode_all.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mirror_queue_mode_exactly.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mirror_queue_mode_nodes.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mirror_queue_slave.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mirror_queue_sync.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_misc.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mnesia.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_mnesia_rename.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_msg_file.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_msg_store.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_msg_store_ets_index.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_msg_store_gc.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_msg_store_index.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_net.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_networking.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_node_monitor.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_nodes.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_parameter_validation.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_plugins.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_plugins_main.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_plugins_usage.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_policies.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_policy.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_policy_validator.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_prelaunch.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_prequeue.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_priority_queue.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_queue_collector.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_queue_consumers.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_queue_decorator.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_queue_index.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_reader.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_recovery_terms.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_registry.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_restartable_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_router.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_runtime_parameter.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_runtime_parameters.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_sasl_report_file_h.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_ssl.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_table.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_trace.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_types.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_upgrade.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_upgrade_functions.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_variable_queue.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_version.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_vhost.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_vm.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/rabbit_writer.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/supervised_lifecycle.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/supervisor2.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/tcp_acceptor.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/tcp_acceptor_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/tcp_listener.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/tcp_listener_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/truncate.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/vm_memory_monitor.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/worker_pool.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/worker_pool_sup.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/ebin/worker_pool_worker.beam
/usr/lib/rabbitmq/lib/rabbitmq-server/include/gm_specs.hrl
/usr/lib/rabbitmq/lib/rabbitmq-server/include/rabbit.hrl
/usr/lib/rabbitmq/lib/rabbitmq-server/include/rabbit_cli.hrl
/usr/lib/rabbitmq/lib/rabbitmq-server/include/rabbit_framing.hrl
/usr/lib/rabbitmq/lib/rabbitmq-server/include/rabbit_msg_store.hrl
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/README
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/amqp_client-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/cowboy-0.5.0-rmq3.5.4-git4b93c2d.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/eldap-3.5.4-gite309de4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/mochiweb-2.7.0-rmq3.5.4-git680dba8.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_amqp1_0-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_auth_backend_ldap-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_auth_mechanism_ssl-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_consistent_hash_exchange-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_federation-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_federation_management-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_management-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_management_agent-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_management_visualiser-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_mqtt-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_shovel-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_shovel_management-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_stomp-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_test-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_tracing-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_web_dispatch-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_web_stomp-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/rabbitmq_web_stomp_examples-3.5.4.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/sockjs-0.3.4-rmq3.5.4-git3132eb9.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/plugins/webmachine-1.10.3-rmq3.5.4-gite9359c7.ez
/usr/lib/rabbitmq/lib/rabbitmq-server/sbin/rabbitmq-defaults
/usr/lib/rabbitmq/lib/rabbitmq-server/sbin/rabbitmq-env
/usr/lib/rabbitmq/lib/rabbitmq-server/sbin/rabbitmq-plugins
/usr/lib/rabbitmq/lib/rabbitmq-server/sbin/rabbitmq-server
/usr/lib/rabbitmq/lib/rabbitmq-server/sbin/rabbitmqctl

%files bin
%defattr(-,root,root,-)
/usr/bin/rabbitmq-plugins
/usr/bin/rabbitmq-server
/usr/bin/rabbitmqctl

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/rabbitmq-server.service
/usr/lib/tmpfiles.d/rabbitmq-server.conf
